CREATE TABLE person
(
    person_id   INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    name        VARCHAR2(20)                                                       NOT NULL,
    surname     VARCHAR2(20)                                                       NOT NULL,
    middle_name VARCHAR2(20),
    birthday    DATE                                                               NOT NULL,
    birthplace  VARCHAR2(100)                                                      NOT NULL,
    person_type VARCHAR2(20) CHECK ( person_type IN ('student', 'professor') ),
    position    VARCHAR2(20) CHECK (position IN ('доцент', 'бакалавр', 'магистр')) NOT NULL -- должность MySQL
);

CREATE TABLE reader_list -- читательский лист MySQL
(
    list_id           INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    registration_date DATE           NOT NULL,                              -- дата регистрации
    person_id         INTEGER UNIQUE NOT NULL REFERENCES person (person_id) -- 1 to 1 to person
);

CREATE TABLE book -- книга MySQL
(
    book_id          INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    title            VARCHAR2(100) NOT NULL, -- название
    author           VARCHAR2(100) NOT NULL, -- автор
    publication_date DATE                    -- Дата публикации
);

CREATE TABLE reader_info -- many to many: чит. лист и книги MySQL
(
    reader_id   INTEGER NOT NULL REFERENCES reader_list (list_id), -- человек
    book_id     INTEGER NOT NULL REFERENCES book (book_id),        -- взял книгу
    obtain_date DATE    NOT NULL,                                  -- когда взял
    returned    DATE                                               -- когда вернул
);

CREATE TABLE conference -- конференция MySQL
(
    conference_id   INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    title           VARCHAR2(100) NOT NULL, -- Наименование конференции
    place           VARCHAR2(100) NOT NULL, -- Место проведения конференции
    conference_date DATE          NOT NULL  -- Дата конференции
);

CREATE TABLE conference_participants -- участники конференции MySQL
(
    -- many to many from persons to conferences
    conference_id INTEGER NOT NULL REFERENCES person (person_id),         -- конференция
    person_id     INTEGER NOT NULL REFERENCES conference (conference_id), -- участник
    PRIMARY KEY (conference_id, person_id)
);

CREATE TABLE project
(
    project_id    INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    title         VARCHAR2(100) NOT NULL, -- Наименование научного проекта
    project_start DATE          NOT NULL, -- Период участия в проекте
    project_end   DATE          NOT NULL
);

CREATE TABLE project_participants -- участники проекта
(
    -- many to many from persons to projects
    project_id INTEGER NOT NULL REFERENCES project (project_id), -- научный проект
    person_id  INTEGER NOT NULL REFERENCES person (person_id),   -- участник
    PRIMARY KEY (project_id, person_id)
);

CREATE TABLE publication -- публикация MySQL
(
    publication_id INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    title          VARCHAR(100) NOT NULL,                               -- Наименование публикации
    type           VARCHAR2(20) CHECK ( type IN ('статья', 'тезисы') ), -- статья/тезисы
    citation_index INTEGER                                              -- Индекс цитирования
);

CREATE TABLE publication_coauthors -- соавторы публикации MySQL
(
    -- many to many from persons to publications
    publication_id INTEGER NOT NULL REFERENCES publication (publication_id), -- публикация
    person_id      INTEGER NOT NULL REFERENCES person (person_id),           -- соавтор
    PRIMARY KEY (publication_id, person_id)
);

CREATE TABLE edition -- издание MySQL
(
    edition_id     INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    title          VARCHAR2(100) NOT NULL, -- Наименование издания
    language       VARCHAR2(30)  NOT NULL, -- Язык издания
    volume         INTEGER       NOT NULL, -- Объём издания -- 5 листов
    place          VARCHAR2(100) NOT NULL, -- Место издания -- Тверь/Москва
    type           VARCHAR2(50)  NOT NULL, -- Тип издания -- вак, ринц ....
    publication_id INTEGER       NOT NULL REFERENCES publication (publication_id)
);

CREATE TABLE work
(
    work_id    INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    position   VARCHAR2(20) NOT NULL, -- должность
    work_start DATE         NOT NULL, -- начало работы
    work_end   DATE,                  -- конец работы
    person_id  INTEGER      NOT NULL REFERENCES person (person_id)
);

CREATE TABLE department -- подразделение
(
    department_id INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    faculty       VARCHAR2(100) NOT NULL, -- Факультет -- Мегафакультет / Факультет учёбы (работы)
    direction     VARCHAR2(100) NOT NULL, -- Направление -- 09.04.04 – Программная инженерия
    specialty     VARCHAR2(100) NOT NULL  -- Специальность -- 09.03.04 – Разработка программно-информационных систем(Академический магистр)
);

CREATE TABLE discipline -- дисциплина
(
    discipline_id INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL, -- название дисциплины
    department_id INTEGER REFERENCES department (department_id)
);

CREATE TABLE work_discipline
(
    -- many to many от должности (работы) к дисциплинам
    work_id       INTEGER NOT NULL REFERENCES work (work_id),
    discipline_id INTEGER NOT NULL REFERENCES discipline (discipline_id)
);

CREATE TABLE schedule -- расписание
(
    schedule_id      INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    classroom        VARCHAR2(100), -- аудитория
    time_description VARCHAR2(200), -- время
    discipline_id    INTEGER REFERENCES discipline (discipline_id)
);

CREATE TABLE education -- учёба
(
    education_id   INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    education_type VARCHAR2(100) NOT NULL, -- вид обучения -- бюджет/контракт
    education_form VARCHAR2(100) NOT NULL, -- форма обучения -- очная/заочная
    qualification  VARCHAR2(100) NOT NULL, -- квалификация -- магистр
    start_date     DATE          NOT NULL, -- дата начала
    end_date       DATE,                   -- дата конца
    course         SMALLINT      NOT NULL, -- курс
    department_id  INTEGER REFERENCES department (department_id)
);

CREATE TABLE person_education
(
    -- many to many от студента к курсам учёбы
    person_id    INTEGER NOT NULL REFERENCES person (person_id),
    education_id INTEGER NOT NULL REFERENCES education (education_id)
);

CREATE TABLE grade -- оценка
(
    grade_id      INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    letter        CHAR(1) CHECK ( letter IN ('A', 'B', 'C', 'D', 'E', 'F') ), -- буква
    grade_date    DATE    NOT NULL,                                           -- дата получения
    person_id     INTEGER NOT NULL REFERENCES person (person_id),
    discipline_id INTEGER NOT NULL REFERENCES discipline (discipline_id),
    UNIQUE (person_id, discipline_id)
);
