CREATE TABLE birthplace
(
    birthplace_id INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    country_key   INTEGER      NOT NULL,
    country_name  VARCHAR2(30) NOT NULL,
    region_key    INTEGER      NOT NULL,
    region_name   VARCHAR2(30) NOT NULL,
    city_key      INTEGER      NOT NULL,
    city_name     VARCHAR2(30) NOT NULL,
    UNIQUE (country_key, region_key, city_key)
);

CREATE TABLE time_t
(
    time_id   INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    year_key  INTEGER      NOT NULL,
    year_name VARCHAR2(30) NOT NULL,
    term_key  INTEGER      NOT NULL,
    term_name VARCHAR2(30) NOT NULL,
    UNIQUE (year_key, term_key)
);

CREATE TABLE fact2
(
    fact2_id      INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    people_count  INTEGER NOT NULL,
    birthplace_id INTEGER NOT NULL REFERENCES birthplace (birthplace_id),
    time_id       INTEGER NOT NULL REFERENCES time_t (time_id),
    UNIQUE (birthplace_id, time_id)
);

CREATE TABLE publishers
(
    publisher_id   INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    country_key    INTEGER      NOT NULL,
    country_name   VARCHAR2(30) NOT NULL,
    city_key       INTEGER      NOT NULL,
    city_name      VARCHAR2(30) NOT NULL,
    publisher_key  INTEGER      NOT NULL,
    publisher_name VARCHAR2(30) NOT NULL
);

CREATE TABLE fact3
(
    fact3_id     INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    people_count INTEGER NOT NULL,
    publisher_id INTEGER NOT NULL REFERENCES publishers (publisher_id),
    time_id      INTEGER NOT NULL REFERENCES time_t (time_id),
    UNIQUE (publisher_id, time_id)
);

CREATE TABLE campus
(
    campus_id    INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    address_key  INTEGER       NOT NULL,
    address_name VARCHAR2(300) NOT NULL
);
