CREATE TABLE birthplace
(
    birthplace_id INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    country_key   INTEGER      NOT NULL,
    country_name  VARCHAR2(30) NOT NULL,
    region_key    INTEGER      NOT NULL,
    region_name   VARCHAR2(30) NOT NULL,
    city_key      INTEGER      NOT NULL,
    city_name     VARCHAR2(30) NOT NULL,
    UNIQUE (country_key, region_key, city_key)
);

CREATE TABLE time_t
(
    time_id   INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    year_key  INTEGER      NOT NULL,
    year_name VARCHAR2(30) NOT NULL,
    term_key  INTEGER      NOT NULL,
    term_name VARCHAR2(30) NOT NULL,
    UNIQUE (year_key, term_key)
);

CREATE TABLE fact2
(
    fact2_id      INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    people_count  INTEGER NOT NULL,
    birthplace_id INTEGER NOT NULL REFERENCES birthplace (birthplace_id),
    time_id       INTEGER NOT NULL REFERENCES time_t (time_id),
    UNIQUE (birthplace_id, time_id)
);

CREATE TABLE publishers
(
    publisher_id   INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    country_key    INTEGER      NOT NULL,
    country_name   VARCHAR2(30) NOT NULL,
    city_key       INTEGER      NOT NULL,
    city_name      VARCHAR2(30) NOT NULL,
    publisher_key  INTEGER      NOT NULL,
    publisher_name VARCHAR2(30) NOT NULL
);

CREATE TABLE fact3
(
    fact3_id     INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    people_count INTEGER NOT NULL,
    publisher_id INTEGER NOT NULL REFERENCES publishers (publisher_id),
    time_id      INTEGER NOT NULL REFERENCES time_t (time_id),
    UNIQUE (publisher_id, time_id)
);

CREATE TABLE campus
(
    campus_id    INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    address_key  INTEGER       NOT NULL,
    address_name VARCHAR2(300) NOT NULL
);

CREATE TABLE fact4
(
    fact4_id    INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    -- average count of persons living in one room
    -- количество проживающих в одной комнате
    room_count  INTEGER NOT NULL,
    -- count of students with only 5 marks (A marks)
    -- количетво обучающихся на 5
    a_mark      INTEGER NOT NULL,
    -- count of students with only 4 and 5 marks (A and B marks)
    -- количетво обучающихся на 4
    a_b_mark    INTEGER NOT NULL,
    -- count of students with 3, 4, 5 marks (A, B, C, D, E marks)
    -- количетво обучающихся на 3
    a_e_mark    INTEGER NOT NULL,
    -- count of students with debts
    -- количетво должников
    debts_count INTEGER NOT NULL,
    -- dimensions
    campus_id   INTEGER NOT NULL REFERENCES campus (campus_id),
    time_id     INTEGER NOT NULL REFERENCES time_t (time_id),
    UNIQUE (campus_id, time_id)
);

CREATE TABLE fact1
(
    fact1_id              INTEGER GENERATED by default on null as IDENTITY PRIMARY KEY,
    -- diploma with honors
    -- предполагаемое количество дипломов с отличием
    honor_diplomas        INTEGER NOT NULL,
    -- usual diploma
    -- предполагаемое количество обычных дипломов
    usual_diplomas        INTEGER NOT NULL,
    -- count of publications
    -- количество публикаций
    publication_count     INTEGER NOT NULL,
    -- count of library cards for students
    -- количество активных читательских билетов среди обучающихся
    student_cards_count   INTEGER NOT NULL,
    -- count of conferences
    -- количество конференций
    conference_count      INTEGER NOT NULL,
    -- count of library cards for employees
    -- количество активных читательских билетов среди сотрудников
    employee_cards_count  INTEGER NOT NULL,
    -- count of people who live in campus
    -- количество проживающих в общежитии
    live_campus_count     INTEGER NOT NULL,
    -- count of people who do not live in campus
    -- количество не проживающих в общежитии
    not_live_campus_count INTEGER NOT NULL,
    -- dimensions
    time_id               INTEGER NOT NULL REFERENCES time_t (time_id) UNIQUE
);
