DROP TABLE fact1 PURGE;
DROP TABLE fact4 PURGE;
DROP TABLE campus PURGE;
DROP TABLE fact3 PURGE;
DROP TABLE publishers PURGE;
DROP TABLE fact2 PURGE;
DROP TABLE time_t PURGE;
DROP TABLE birthplace PURGE;
