ALTER SESSION SET "_ORACLE_SCRIPT"= true;

CREATE USER ifmo IDENTIFIED BY ifmo;

GRANT RESOURCE TO ifmo;
GRANT CONNECT TO ifmo;
GRANT CREATE SESSION TO ifmo;
GRANT CREATE VIEW TO ifmo;
GRANT CREATE TABLE TO ifmo;
GRANT UNLIMITED TABLESPACE TO ifmo;
GRANT olap_user TO ifmo;
-- GRANT CREATE CUBE DIMENSION TO ifmo;
