version: '3.7'

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    depends_on:
      - pg
      - mysql
      - mongo
    restart: on-failure

  pg:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: on-failure

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: on-failure

  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    restart: on-failure
