version: '3.7'

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: on-failure

  pg:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: on-failure

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    restart: on-failure

  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    restart: on-failure
