DROP table person CASCADE CONSTRAINTS;
DROP table work CASCADE CONSTRAINTS;
DROP table discipline CASCADE CONSTRAINTS;
DROP table schedule CASCADE CONSTRAINTS;
DROP table department CASCADE CONSTRAINTS;
DROP table education CASCADE CONSTRAINTS;
DROP table grade CASCADE CONSTRAINTS;
DROP table person_education CASCADE CONSTRAINTS;
